version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21

  pre_build:
    commands:
      - echo "Checking Java version..."
      - java -version
      - echo "Checking Maven version..."
      - mvn -version
      - echo "Logging in to Amazon ECR..."
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR_URI=${ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${ECR_URI}

  build:
    commands:
      - echo "Starting Maven build..."
      - mvn clean package
      - echo "Building Docker image..."
      - docker build -t codebuild-pipelinw:${CODEBUILD_BUILD_NUMBER} .
      - docker tag codebuild-pipelinw:${CODEBUILD_BUILD_NUMBER} ${ECR_URI}/codebuild-pipelinw:${CODEBUILD_BUILD_NUMBER}

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push ${ECR_URI}/codebuild-pipelinw:${CODEBUILD_BUILD_NUMBER}
      - echo "Docker image pushed successfully!"
      - echo "Image URI:"
      - echo "${ECR_URI}/codebuild-pipelinw:${CODEBUILD_BUILD_NUMBER}"
